print("A quadratic equation is of the form: ax^2 + bx + c, where a, b and c are constants.")
print("Using this python program, you can find the root(s) of any quadratic equation.")
print("Enter the value(s) of the given constant(s):")
a=int(input("a="))
b=int(input("b="))
c=int(input("c="))
d=((b**2)-(4*a*c))
d1=(d**(0.5))
if(d<0):
    im_root1=(-b+d1)/(2*a)
    im_root2=(-b-d1)/(2*a)
    #print("First root: ", complex(im_root1))
    #print("Second root: ", complex(im_root2))
    print("Here, the discriminant is less than 0, therefore")
    print("the first imaginary root: ", round(im_root1.real,2) + round(im_root1.imag,2)*1j)
    print("and the second imaginary root: ", round(im_root2.real,2) + round(im_root2.imag,2)*1j)
elif(d>0):
    rl_root1=(-b+d1)/(2*a)
    rl_root2=(-b-d1)/(2*a)
    print("Here, the discriminant is greater than 0, therefore")
    print("the first real root: ", round(rl_root1,2))
    print("the second real root: ", round(rl_root2,2))
elif(d==0):
    only_rlroot=(-b+d1)/(2*a)
    print("Here, the discriminant is equal to 0, therefore")
    print("the only real root: ", round(only_rlroot,2))
